services:
  web:
    image: nginx:latest
    ports:
      - "8081:80"
    networks:
      - default
    volumes:
      - ./app/dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf # Like "COPY"
    deploy:
      replicas: 3,
      update_config:
        parallelism: 1
        delay: 10s

  api:
    image: node:22
    working_dir: /app
    environment:
     - API_PORT = 3000
    networks:
      - default
    volumes:
      - ./api:/app
    depends_on:
      - db
    command: ["sh", "-c", "npm install && node index.js"]

  db:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=123456
      - MARIADB_DATABASE=in-class-db
      - MARIADB_USER=in-class-user
      - MARIADB_PASSWORD=654321
    networks:
      - default
    volumes:
      - database:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
networks:
  default:
    driver: bridge

volumes:
  nginx:
  database:
