CREATE TABLE messages {
    id INT AUTO_INCREMENT PRIMARY KEy,
    name VARCHAR(200) NOT NULL,
    email VARCHAR(200) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
}